'use strict';

/** Runtime injected into the wrapped template document (iframe). */
module.exports = function wrapperRuntimeSource() {
  return [
    '(function () {',
    '  function parseData() {',
    '    var node = document.getElementById("payment-template-i18n");',
    '    if (!node) return { locales: {}, defaultLocale: "en-US" };',
    '    return JSON.parse(node.textContent);',
    '  }',
    '  function lookup(obj, key) {',
    '    return key.split(".").reduce(function (acc, part) {',
    '      if (acc == null) return undefined;',
    '      return acc[part];',
    '    }, obj);',
    '  }',
    '  function localeKeys(locales) {',
    '    return Object.keys(locales);',
    '  }',
    '  function resolveLocale(requested, locales, defaultLocale) {',
    '    if (locales[requested]) return requested;',
    '    var lang = requested.split("-")[0];',
    '    var matches = localeKeys(locales).filter(function (tag) {',
    '      return tag === lang || tag.indexOf(lang + "-") === 0;',
    '    });',
    '    if (matches.length === 1) return matches[0];',
    '    if (matches.length > 1) {',
    '      var defaultLang = defaultLocale.split("-")[0];',
    '      if (defaultLang === lang && locales[defaultLocale]) return defaultLocale;',
    '      return matches[0];',
    '    }',
    '    return defaultLocale;',
    '  }',
    '  function applyLocale(localeTag) {',
    '    var payload = parseData();',
    '    var resolved = resolveLocale(localeTag, payload.locales, payload.defaultLocale);',
    '    var table = payload.locales[resolved] || payload.locales[payload.defaultLocale] || {};',
    '    document.querySelectorAll("[data-i18n]").forEach(function (node) {',
    '      var key = node.getAttribute("data-i18n");',
    '      if (!key) return;',
    '      var value = lookup(table, key);',
    '      if (typeof value === "string") node.textContent = value;',
    '    });',
    '  }',
    '  function resetDocumentBox() {',
    '    var root = document.documentElement;',
    '    var body = document.body;',
    '    if (root) {',
    '      root.style.margin = "0";',
    '      root.style.padding = "0";',
    '    }',
    '    if (body) {',
    '      body.style.margin = "0";',
    '      body.style.padding = "0";',
    '    }',
    '  }',
    '  function measureHeight() {',
    '    resetDocumentBox();',
    '    var body = document.body;',
    '    if (!body) return 0;',
    '    var content = body.firstElementChild;',
    '    if (content) {',
    '      var rect = content.getBoundingClientRect();',
    '      var styles = window.getComputedStyle(content);',
    '      var marginBottom = parseFloat(styles.marginBottom) || 0;',
    '      return Math.ceil(rect.height + marginBottom);',
    '    }',
    '    return Math.ceil(Math.max(body.scrollHeight, body.offsetHeight));',
    '  }',
    '  var lastHeight = -1;',
    '  function postHeight() {',
    '    if (!window.parent || window.parent === window) return;',
    '    var height = measureHeight();',
    '    if (height === lastHeight) return;',
    '    lastHeight = height;',
    '    window.parent.postMessage({ height: height }, "*");',
    '  }',
    '  function schedulePostHeight() {',
    '    requestAnimationFrame(function () {',
    '      requestAnimationFrame(postHeight);',
    '    });',
    '  }',
    '  function whenImagesReady(callback) {',
    '    var images = Array.prototype.slice.call(document.images || []);',
    '    if (!images.length) {',
    '      callback();',
    '      return;',
    '    }',
    '    var pending = 0;',
    '    images.forEach(function (image) {',
    '      if (image.complete) return;',
    '      pending += 1;',
    '      image.addEventListener("load", function onLoad() {',
    '        image.removeEventListener("load", onLoad);',
    '        pending -= 1;',
    '        if (pending === 0) callback();',
    '      });',
    '      image.addEventListener("error", function onError() {',
    '        image.removeEventListener("error", onError);',
    '        pending -= 1;',
    '        if (pending === 0) callback();',
    '      });',
    '    });',
    '    if (pending === 0) callback();',
    '  }',
    '  function observeLayout() {',
    '    if (typeof ResizeObserver !== "function") return;',
    '    var observer = new ResizeObserver(schedulePostHeight);',
    '    if (document.body) observer.observe(document.body);',
    '    if (document.documentElement) observer.observe(document.documentElement);',
    '    if (document.body && document.body.firstElementChild) {',
    '      observer.observe(document.body.firstElementChild);',
    '    }',
    '  }',
    '  function boot() {',
    '    var payload = parseData();',
    '    applyLocale(payload.defaultLocale);',
    '    window.addEventListener("message", function (event) {',
    '      var data = event.data;',
    '      if (!data) return;',
    '      if (data.type === "payment-template:measure") {',
    '        lastHeight = -1;',
    '        schedulePostHeight();',
    '        return;',
    '      }',
    '      if (typeof data.locale === "string") {',
    '        applyLocale(data.locale);',
    '        schedulePostHeight();',
    '      }',
    '    });',
    '    resetDocumentBox();',
    '    observeLayout();',
    '    schedulePostHeight();',
    '    whenImagesReady(schedulePostHeight);',
    '    window.addEventListener("load", schedulePostHeight);',
    '  }',
    '  if (document.readyState === "loading") {',
    '    document.addEventListener("DOMContentLoaded", boot);',
    '  } else {',
    '    boot();',
    '  }',
    '})();',
  ].join('\n');
};
