'use strict';

/**
 * Returns the runtime script injected into the wrapped template document.
 *
 * Parity: must match production checkout iframe behavior — locale resolution
 * (exact tag → language prefix → defaultLocale), data-i18n apply, reactive
 * height via ResizeObserver, postMessage({ height }) to the host, and listening
 * for postMessage({ locale }) from the host.
 *
 * Maintenance: keep in sync with wrap-template.js. Target home is a shared
 * package (@vtex/payment-template-wrap-runtime) imported by the handler and
 * payment-mocker once the handler wrap stabilizes.
 */
const { resolveLocale } = require('./resolve-locale');

module.exports = function wrapperRuntimeSource() {
  return [
    '(function () {',
    '  function parseData() {',
    '    var node = document.getElementById("payment-template-i18n");',
    '    if (!node) return { locales: {}, defaultLocale: "en-US" };',
    '    return JSON.parse(node.textContent);',
    '  }',
    '  function lookup(obj, key) {',
    '    return key.split(".").reduce(function (acc, part) {',
    '      if (acc == null) return undefined;',
    '      return acc[part];',
    '    }, obj);',
    '  }',
    '  var resolveLocale = ' + resolveLocale.toString() + ';',
    '  function applyLocale(localeTag) {',
    '    var payload = parseData();',
    '    var resolved = resolveLocale(localeTag, payload.locales, payload.defaultLocale);',
    '    document.documentElement.lang = resolved;',
    '    var table = payload.locales[resolved] || payload.locales[payload.defaultLocale] || {};',
    '    document.querySelectorAll("[data-i18n]").forEach(function (node) {',
    '      var key = node.getAttribute("data-i18n");',
    '      if (!key) return;',
    '      var value = lookup(table, key);',
    '      if (typeof value === "string") node.textContent = value;',
    '    });',
    '  }',
    '  // Deliberate design decision, not a bug to "fix" if it comes up again in',
    '  // review: resetDocumentBox applies margin/padding/display via INLINE',
    '  // style (element.style.*), which sits below author CSS in specificity.',
    '  // A template author who writes `body { margin: 24px !important }` (or',
    '  // `display: block !important`) in their own style.css can and will win',
    '  // over this reset — that is accepted and expected, since it is the',
    '  // author deliberately overriding the host-provided default from their',
    '  // own stylesheet, not an accident. This function does not fight',
    '  // `!important` on purpose.',
    '  function resetDocumentBox() {',
    '    var root = document.documentElement;',
    '    var body = document.body;',
    '    if (root) {',
    '      root.style.margin = "0";',
    '      root.style.padding = "0";',
    '    }',
    '    if (body) {',
    '      body.style.margin = "0";',
    '      body.style.padding = "0";',
    '      if (window.getComputedStyle(body).display === "block") {',
    '        body.style.display = "flow-root";',
    '      }',
    '    }',
    '  }',
    '  function measureHeight() {',
    '    if (!document.body) return 0;',
    '    resetDocumentBox();',
    '    return Math.ceil(document.body.getBoundingClientRect().height);',
    '  }',
    '  var lastHeight = -1;',
    '  function postHeight() {',
    '    if (!window.parent || window.parent === window) return;',
    '    var height = measureHeight();',
    '    if (height === lastHeight) return;',
    '    lastHeight = height;',
    '    window.parent.postMessage({ height: height }, "*");',
    '  }',
    '  function schedulePostHeight() {',
    '    requestAnimationFrame(function () {',
    '      requestAnimationFrame(postHeight);',
    '    });',
    '  }',
    '  function whenImagesReady(callback) {',
    '    var images = Array.prototype.slice.call(document.images || []);',
    '    if (!images.length) {',
    '      callback();',
    '      return;',
    '    }',
    '    var pending = 0;',
    '    images.forEach(function (image) {',
    '      if (image.complete) return;',
    '      pending += 1;',
    '      image.addEventListener("load", function onLoad() {',
    '        image.removeEventListener("load", onLoad);',
    '        pending -= 1;',
    '        if (pending === 0) callback();',
    '      });',
    '      image.addEventListener("error", function onError() {',
    '        image.removeEventListener("error", onError);',
    '        pending -= 1;',
    '        if (pending === 0) callback();',
    '      });',
    '    });',
    '    if (pending === 0) callback();',
    '  }',
    '  function observeLayout() {',
    '    if (typeof ResizeObserver !== "function") return;',
    '    var observer = new ResizeObserver(schedulePostHeight);',
    '    if (document.body) observer.observe(document.body);',
    '    if (document.documentElement) observer.observe(document.documentElement);',
    '    if (document.body && document.body.firstElementChild) {',
    '      observer.observe(document.body.firstElementChild);',
    '    }',
    '  }',
    '  function boot() {',
    '    var payload = parseData();',
    '    applyLocale(payload.defaultLocale);',
    '    window.addEventListener("message", function (event) {',
    '      if (event.source !== window.parent) return;',
    '      var data = event.data;',
    '      if (!data) return;',
    '      if (data.type === "payment-template:measure") {',
    '        lastHeight = -1;',
    '        schedulePostHeight();',
    '        return;',
    '      }',
    '      if (typeof data.locale === "string") {',
    '        applyLocale(data.locale);',
    '        schedulePostHeight();',
    '      }',
    '    });',
    '    resetDocumentBox();',
    '    observeLayout();',
    '    schedulePostHeight();',
    '    whenImagesReady(schedulePostHeight);',
    '    window.addEventListener("load", schedulePostHeight);',
    '  }',
    '  if (document.readyState === "loading") {',
    '    document.addEventListener("DOMContentLoaded", boot);',
    '  } else {',
    '    boot();',
    '  }',
    '})();',
  ].join('\n');
};
